CREATE TABLE `cleaning_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('entrances','residence','other') NOT NULL,
	`status` enum('pending','reviewed','completed','cancelled') NOT NULL DEFAULT 'pending',
	`userId` int NOT NULL,
	`userOpenId` varchar(64) NOT NULL,
	`floors` int,
	`aptsPerFloor` int,
	`rooms` int,
	`sqm` decimal(8,2),
	`residenceType` enum('apartment','house'),
	`requirements` text,
	`description` text,
	`imageUrl` text,
	`proposedPrice` decimal(10,2),
	`estimatedVolume` varchar(64),
	`contactPhone` varchar(32),
	`contactEmail` varchar(320),
	`district` varchar(128),
	`address` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cleaning_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userOpenId` varchar(64) NOT NULL,
	`type` enum('purchase','transfer_in','transfer_out','deduction','bonus','admin_add','admin_deduct') NOT NULL,
	`creditType` enum('standard','recycling') NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`bonusAmount` decimal(10,2) NOT NULL DEFAULT '0.00',
	`totalAmount` decimal(10,2) NOT NULL,
	`pricePaid` decimal(10,2),
	`stripeSessionId` varchar(256),
	`stripePaymentIntentId` varchar(256),
	`transferToUserId` int,
	`transferToOpenId` varchar(64),
	`transferFromUserId` int,
	`transferFromOpenId` varchar(64),
	`requestId` int,
	`note` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `transactions_id` PRIMARY KEY(`id`)
);
